Repository 4jo-Phoenix/Alcohol_hub, pull requests merged in 2024-03, with the labels that each got.

#25 [New Feature] Fair 정보 게시글 추가 기능
  ahub-fair-and-news/build.gradle
  ahub-fair-and-news/src/main/java/com/teamphoenix/AhubFairAndNewsApplication.java
  ahub-fair-and-news/src/main/java/com/teamphoenix/ahub/fair/command/dto/FairDTO.java
  ahub-fair-and-news/src/main/java/com/teamphoenix/ahub/fair/command/entity/Fair.java
  ahub-fair-and-news/src/main/java/com/teamphoenix/ahub/fair/command/repository/FairRepository.java
  ahub-fair-and-news/src/main/java/com/teamphoenix/ahub/fair/command/service/FairService.java
  ahub-fair-and-news/src/main/java/com/teamphoenix/ahub/news/command/entity/News.java
  ahub-fair-and-news/src/main/java/com/teamphoenix/ahub/news/command/service/NewsService.java
  ahub-fair-and-news/src/main/java/com/teamphoenix/fairnews/AhubFairAndNewsApplication.java
  ahub-fair-and-news/src/main/java/com/teamphoenix/fairnews/fair/query/FairMapper.java
  ahub-fair-and-news/src/main/java/com/teamphoenix/fairnews/fair/query/FairService.java
  ahub-fair-and-news/src/main/java/com/teamphoenix/fairnews/fair/query/common/Fair.java
  ahub-fair-and-news/src/main/java/com/teamphoenix/fairnews/fair/query/common/FairConfiguration.java
  ahub-fair-and-news/src/main/java/com/teamphoenix/fairnews/news/query/common/News.java
  ahub-fair-and-news/src/main/java/com/teamphoenix/fairnews/news/query/common/NewsConfiguration.java
  ahub-fair-and-news/src/main/java/com/teamphoenix/fairnews/news/query/common/NewsDTO.java
  ahub-fair-and-news/src/main/resources/application.yaml
  ahub-fair-and-news/src/main/resources/com/teamphoenix/fairnews/fair/query/FairMapper.xml
  ahub-fair-and-news/src/test/java/com/teamphoenix/ahub/fair/command/service/FairServiceTest.java
  ahub-fair-and-news/src/test/java/com/teamphoenix/fairnews/AhubFairAndNewsApplicationTests.java
  ahub-fair-and-news/src/test/java/com/teamphoenix/fairnews/fair/query/FairServiceTest.java
Labels: enhancement, Improvement

#45 [New Feature] Fair & News 프로젝트 Fair Command CRUD 기능 추가
  ahub-fair-and-news/src/main/java/com/teamphoenix/ahub/fair/command/aggregate/Fair.java
  ahub-fair-and-news/src/main/java/com/teamphoenix/ahub/fair/command/commandRequest.http
  ahub-fair-and-news/src/main/java/com/teamphoenix/ahub/fair/command/controller/FairController.java
  ahub-fair-and-news/src/main/java/com/teamphoenix/ahub/fair/command/dto/FairDTO.java
  ahub-fair-and-news/src/main/java/com/teamphoenix/ahub/fair/command/service/FairService.java
  ahub-fair-and-news/src/main/java/com/teamphoenix/ahub/fair/command/service/FairServiceImpl.java
  ahub-fair-and-news/src/main/java/com/teamphoenix/ahub/fair/command/vo/RegistFairInfo.java
  ahub-fair-and-news/src/main/java/com/teamphoenix/ahub/fair/command/vo/ResponseUrlMessage.java
  ahub-fair-and-news/src/test/java/com/teamphoenix/ahub/fair/command/service/FairServiceImplImplTest.java
Labels: enhancement

#49 [New Feature] Eureka Server 용 프로젝트 생성
  eureka-server/.gitignore
  eureka-server/build.gradle
  eureka-server/gradle/wrapper/gradle-wrapper.jar
  eureka-server/gradle/wrapper/gradle-wrapper.properties
  eureka-server/gradlew
  eureka-server/gradlew.bat
  eureka-server/settings.gradle
  eureka-server/src/main/java/com/teamphoneix/eurekaserver/EurekaServerApplication.java
  eureka-server/src/main/resources/application.yml
  eureka-server/src/test/java/com/teamphoneix/eurekaserver/EurekaServerApplicationTests.java
Labels: enhancement

#58 [Improvement] Member 프로젝트 업데이트
  ahub-member/src/main/java/com/teamphoenix/ahub/query/controller/MemberController.java
  ahub-member/src/main/java/com/teamphoenix/ahub/query/dto/MemberDTO.java
  ahub-member/src/main/java/com/teamphoenix/ahub/query/service/MemberService.java
  ahub-member/src/main/java/com/teamphoenix/ahub/query/vo/LoginResponseMember.java
  ahub-member/src/main/java/com/teamphoenix/ahub/query/vo/MyProfileResponseMember.java
  ahub-member/src/main/resources/com/teamphoenix/ahub/query/mapper/MemberMapper.xml
  ahub-member/src/test/java/com/teamphoenix/ahub/query/service/MemberServiceTests.java
Labels: bug

#59 [Improvement] LocalDateTime에 format 지정, 사용되지 않는 common 패키지 삭제
  ahub-member/src/main/java/com/teamphoenix/ahub/command/controller/MemberController.java
  ahub-member/src/main/java/com/teamphoenix/ahub/common/entity/MemberInfo.java
  ahub-member/src/test/java/com/teamphoenix/ahub/MemberServiceTests.java
Labels: Improvement

#61 [Project Update] Member 프로젝트 Feign Client 사용을 위한 gateway routes 설정
  gateway-server/src/main/resources/application.yml
Labels: documentation

#85 Feature/member logout JWT Filter, JWT Util 추가
  .idea/vcs.xml
  ahub-member/.idea/compiler.xml
  ahub-member/.idea/dataSources.xml
  ahub-member/.idea/gradle.xml
  ahub-member/build.gradle
  ahub-member/src/main/java/com/teamphoenix/ahub/member/command/aggregate/MemberInfo.java
  ahub-member/src/main/java/com/teamphoenix/ahub/member/command/controller/MemberController.java
  ahub-member/src/main/java/com/teamphoenix/ahub/member/command/security/AuthenticationFilter.java
  ahub-member/src/main/java/com/teamphoenix/ahub/member/command/security/JwtFilter.java
  ahub-member/src/main/java/com/teamphoenix/ahub/member/command/security/JwtUtil.java
  ahub-member/src/main/java/com/teamphoenix/ahub/member/command/security/WebSecurityConfig.java
  ahub-member/src/main/java/com/teamphoenix/ahub/member/command/service/MemberService.java
  ahub-member/src/main/java/com/teamphoenix/ahub/member/command/service/MemberServiceImpl.java
  ahub-member/src/main/java/com/teamphoenix/ahub/member/command/vo/RequestMember.java
  ahub-member/src/main/java/com/teamphoenix/ahub/member/query/controller/MemberController.java
  ahub-member/src/main/java/com/teamphoenix/ahub/member/query/dto/MemberDTO.java
  ahub-member/src/main/java/com/teamphoenix/ahub/member/query/vo/MyProfileResponseMember.java
  ahub-member/src/main/java/com/teamphoenix/ahub/member/redis/RedisConfig.java
  ahub-member/src/main/java/com/teamphoenix/ahub/member/redis/RedisProperties.java
  ahub-member/src/main/resources/application.yml
  ahub-member/src/main/resources/com/teamphoenix/ahub/member/query/mapper/MemberMapper.xml
  ahub-member/src/test/java/com/teamphoenix/ahub/member/query/service/MemberServiceImplTests.java
  gateway-server/src/main/resources/application.yml
  pj-eureka-server/.gitignore
  pj-eureka-server/src/main/resources/application.yml
Labels: enhancement
